"""empty message

Revision ID: 3da28e08dec9
Revises: e97a15077412
Create Date: 2023-03-27 11:04:28.501352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da28e08dec9'
down_revision = 'e97a15077412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Idiom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hanja', sa.String(), nullable=True),
    sa.Column('hangeul', sa.Text(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hanja')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Idiom')
    # ### end Alembic commands ###
