"""empty message

Revision ID: e97a15077412
Revises: 
Create Date: 2023-02-05 02:47:08.929540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97a15077412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idiom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hanja', sa.String(), nullable=False),
    sa.Column('hangeul', sa.Text(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hangeul'),
    sa.UniqueConstraint('hanja')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idiom')
    # ### end Alembic commands ###
