"""empty message

Revision ID: fe6acac34a21
Revises: 
Create Date: 2023-02-04 22:55:52.768040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe6acac34a21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idiom', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('idiom', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idiom', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('idiom', 'created_at')
    # ### end Alembic commands ###
